version: '3'

volumes:
  trader-bot-db-data: {}

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - trader-bot-db-data:/var/lib/postgresql/data
      - ./tools/psql/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
